### Cria um comando
POST http://127.0.0.1:3000/application/sistema/1/comando/10
Content-Type: application/json

{
    "name": "comando 10",
    "parametros": "parm2",
    "retorno": "comando xpto executado com sucesso"
}

### Obtem um comando
GET http://127.0.0.1:3000/application/sistema/2/comando/21


### Execucao de um sistema
GET http://127.0.0.1:3000/application/sistema/2/comando/21/execute


### Atualiza um comando
PUT http://127.0.0.1:3000/application/sistema/1/comando/1
Content-Type: application/json

{
    "name": "comando 1",
    "parametros": "parm1 alterado",
    "retorno": "comando xpto executado com sucesso"
}

### Deleta o comando
DELETE http://127.0.0.1:3000/application/sistema/1/comando/1
