### Cria um SISTEMA
POST http://127.0.0.1:3000/application/sistema/1
Content-Type: application/json

{
    "name": "sistema 1",
    "environment": "prod"
}

### Cria um varios sistemas
POST http://127.0.0.1:3000/application/sistemas/
Content-Type: application/json

{
  "sistemas": [
   {
    "id": 2,
    "name": "sistema 2",
    "environment": "prod"
   },
   {
    "id": 3,
    "name": "sistema 3",
    "environment": "prod"
   },
   {
    "id": 4,
    "name": "sistema 4",
    "environment": "prod"
   }
 ]
}

### Obtem um SISTEMA
GET http://127.0.0.1:3000/application/sistema/2


### Obtem os comandos de um sistema
GET http://127.0.0.1:3000/application/sistema/1/comandos


### Atualiza um USUARIO
PUT http://127.0.0.1:3000/application/sistema/1
Content-Type: application/json

{
    "name": "sistema 1",
    "environment": "tes"
}

### Deleta o usuario
DELETE http://127.0.0.1:3000/application/sistema/1
