### Cria um SISTEMA
POST http://127.0.0.1:3000/application/sistema/2
Content-Type: application/json

{
    "name": "sistema 1",
    "environment": "prod"
}

### Cria varios sistemas
POST http://127.0.0.1:3000/application/sistemas/
Content-Type: application/json

{
  "sistemas": [
   {
    "id": 2,
    "name": "sistema 2",
    "environment": "prod"
   },
   {
    "id": 3,
    "name": "sistema 3",
    "environment": "prod"
   },
   {
    "id": 4,
    "name": "sistema 4",
    "environment": "prod"
   }
 ]
}


### Obtem todos os sistemas
GET http://127.0.0.1:3000/application/sistemas/



### Obtem um SISTEMA
GET http://127.0.0.1:3000/application/sistema/2


### Obtem os comandos de um sistema
GET http://127.0.0.1:3000/application/sistema/2/comandos


### Obtem os comandos de um sistema
POST http://127.0.0.1:3000/application/sistema/2/comandos
Content-Type: application/json

{
  "comandos": [
   {
    "name": "comando 12",
    "parametros": "prod init 22",
    "retorno": "comando xpto executado com sucesso"
   },
   {
    "name": "comando 122",
    "parametros": "tes init 23",
    "retorno": "comando xpto executado com sucesso"
   },
   {
    "name": "comando 4",
    "parametros": "hom init 33",
    "retorno": "erro ao executar"
   }
 ]
}


### Atualiza um USUARIO
PUT http://127.0.0.1:3000/application/sistema/1
Content-Type: application/json

{
    "name": "sistema 1",
    "environment": "tes"
}

### Deleta o usuario
DELETE http://127.0.0.1:3000/application/sistema/2
