### Cria um USUARIO
POST http://127.0.0.1/application/user/register
Content-Type: application/json

{
    "email": "laurosn@gmail.com",
    "password": "devops"
}


### Deleta o usuario
DELETE http://127.0.0.1:3000/application/user/Doe/John
