@hostname = 127.0.0.1
@port = 80
@host = {{hostname}}:{{port}}
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mzc4MzQ2NDEsImlhdCI6MTYzNzgzNDM0MSwic3ViIjoxfQ.4w7SqgY4oSex00H9B3RSUcLAtc1RJC3E4ty3ROD4EMY

### Cria um USUARIO
POST http://{{host}}/application/user/register
Content-Type: application/json

{
    "email": "laurosn@gmail.com",
    "password": "devops"
}

### Login do USUARIO
POST http://{{host}}/application/user/login
Content-Type: application/json

{
    "email": "laurosn@gmail.com",
    "password": "devops"
}

### Deleta o usuario
DELETE http://{{host}}/application/user/Doe/John


### Obtem todos os sistemas
GET http://{{host}}/application/users
Authorization: token {{token}}
