version: '3.3'

services:
  server:
    build:
      context: .
      dockerfile: src/Dockerfile.server
    env_file:
      - .env
#    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - "8000:8000"
#      - 3000:3000
#    command: python src/server.py
#    command: gunicorn -w 1 -b :8000 src/server:server

  nginx:
      build: ./nginx
      ports:
        - 80:80
      depends_on:
        - server

  dbdata:
    image: busybox
    volumes:
      - dbdatavol:/var/lib/postgresql/data
  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dbdatavol:/var/lib/postgresql/data

  testserver:
    env_file: .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:9.4
volumes:
  dbdatavol: